### ISSUE TITLE
Cannot install package due to issue with fasttext

### ISSUE THREAD

**Issue by AnesBenmerzoug** [konstantinjdobler/focus#4]
I am trying to try and compare different embedding initialization methods and I wanted to try out your method but unfortunately I could get it to install. I thought it was at first an issue with Poetry so I tried using pip directly but even then the error persisted.

# System

- Ubuntu 22.04.2 LTS
- Python 3.10
- Poetry 1.7.0

# How to reproduce

```shell
$ pip install --no-cache-dir deepfocus
```

<details>
<summary>Click to toggle contents of `stack trace`</summary>

```shell
Collecting deepfocus
  Downloading deepfocus-1.0.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: torch in /home/abenmerzoug/.cache/pypoetry/virtualenvs/language-transfer-qhLQOQZl-py3.10/lib/python3.10/site-packages (from deepfocus) (2.1.0+cu118)
Requirement already satisfied: transformers>=4.0.0 in /home/abenmerzoug/.cache/pypoetry/virtualenvs/language-transfer-qhLQOQZl-py3.10/lib/python3.10/site-packages (from deepfocus) (4.35.0)
Requirement already satisfied: datasets in /home/abenmerzoug/.cache/pypoetry/virtualenvs/language-transfer-qhLQOQZl-py3.10/lib/python3.10/site-packages (from deepfocus) (2.14.6)
Requirement already satisfied: entmax in /home/abenmerzoug/.cache/pypoetry/virtualenvs/language-transfer-qhLQOQZl-py3.10/lib/python3.10/site-packages (from deepfocus) (1.1)
Collecting fasttext (from deepfocus)
  Downloading fasttext-0.9.2.tar.gz (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.8/68.8 kB 3.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      /home/abenmerzoug/.cache/pypoetry/virtualenvs/language-transfer-qhLQOQZl-py3.10/bin/python: No module named pip
      Traceback (most recent call last):
        File "<string>", line 38, in __init__
      ModuleNotFoundError: No module named 'pybind11'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/abenmerzoug/.cache/pypoetry/virtualenvs/language-transfer-qhLQOQZl-py3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/abenmerzoug/.cache/pypoetry/virtualenvs/language-transfer-qhLQOQZl-py3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/abenmerzoug/.cache/pypoetry/virtualenvs/language-transfer-qhLQOQZl-py3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-jw5vx3r7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-jw5vx3r7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-jw5vx3r7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-jw5vx3r7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 72, in <module>
        File "<string>", line 41, in __init__
      RuntimeError: pybind11 install failed.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
</details>

# Possible solution

Use [fasttext-wheel](https://pypi.org/project/fasttext-wheel/) package instead of [fasttext](https://pypi.org/project/fasttext/) package as a dependency.

**Comment by konstantinjdobler** [comment]
Sorry about this! As a quick fix, could you try if `pip install wheel` before installing `deepfocus` works (solution from https://github.com/facebookresearch/fastText/issues/512#issuecomment-1718315762)? 

I'll have a look into properly updating the dependencies as well.

**Comment by AnesBenmerzoug** [comment]
Thanks @konstantinjdobler for the quick reply! That works and actually allows me to install fasttext and subsequently deepfocus, but only when using pip directly. It still doesn't work with poetry.

I would still recommend switching to fasttext-wheel until a better alternative comes up.

Perhaps a much better alternative would be to use the [fasttext implementation](https://radimrehurek.com/gensim/auto_examples/tutorials/run_fasttext.html) in [Gensim](https://radimrehurek.com/gensim/index.html), if I'm not mistaken it does not depend on the fasttext package.

**Comment by konstantinjdobler** [comment]
`fasttext-wheel` looks good! I don't want to change the code too much from what I used to produce the results in the paper right now.

**Comment by RubTalha** [comment]
https://stackoverflow.com/a/77630437/13086128
